<!DOCTYPE html>
<html>
<head>
<title>艺生活</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no"/>
<script src=<?php $path; ?>"js/jquery.js"></script>
<link rel="stylesheet" href=<?php $path; ?>"css/reset.css" type="text/css">
<link rel="stylesheet" href=<?php $path; ?>"css/layout.css" type="text/css">
</head>
<body> 
	<div class="container loginbox">
		<div class="loginbox_top">点我点我，一键绑定!</div>
		<div class="loginbox_c">
			<div class="loginfrm">
				<div class="loginfrmli"><span class="loginfrmli_span">用户：</span><input type="" class="loginfrm_ipt" placeholder="用户名" /></div>
				<div class="loginfrmli"><span class="loginfrmli_span">密码：</span><input type="password" class="loginfrm_ipt" placeholder="密码" /></div>
			</div>
			<button class="loginfrmbtn">绑定</button>
		</div>
		<div class="loginbox_bottom">
			<p>神马？你们还没注册?</p>
			<a href="" class="login_bind">注册</a>
		</div>
	</div>
</body>
</html>	